export const DAILY_TIPS: string[] = [
  "🔥 *Career Tip:* 'Start networking early, but don’t just collect coffee chats—build real relationships!' – [2Y MBA]",
  "📚 *Academics Hack:* 'If a class is heavy on cases, form a study group early. Trust me, it saves time.' – [KFBS Alum]",
  "💼 *Internship Advice:* 'Treat recruiting like a marathon, not a sprint. Stay consistent and don’t compare your timeline to others.' – [Recent Grad]",
  "☕ *Chapel Hill Tip:* 'Best quiet Bagel shop in Chapel Hill? Try Brandwein's Bagels.' – [2Y MBA]",
  "🎶 *De-Stress Playlist:* 'Feeling overwhelmed? Lo-fi beats or Afrobeats can help you refocus.' – [KFBS Student]",
  "🔥 Wellness Tip: 'Rest is important. Yes, the job and academics are important too, but you need to be in good health too. So be intentional about rest and find activities you can do outside school.' – [2Y MBA]",
  "📚 Recruiting Hack: 'Install the 'Ultimate H1B Sponsor Checker' extension on your Chrome. It's helpful to filter out companies that sponsor.' – [2Y MBA]",
  "☕ Chapel Hill Tip: 'Need a quiet study spot away from campus? Try Johnny's Gone Fishing in Carrboro.' – [2Y MBA]",
  "🎶 De-Stress Playlist: 'Music does wonders. Have your playlist or mix on your favourite music app. It can be a boost on those days that don't feel so great.' – [2Y MBA]",
  "🌍 Culture Shock Tip: 'Feeling homesick? Cook a traditional meal and invite your classmates over for a Pot luck—builds friendships and eases homesickness.' – [1Y MBA]",
  "💰 Finance Hack: 'Open a secured credit card early to build US credit history—essential for post-MBA housing and car purchases.' – [KFBS Alum]",
  "👔 Networking Strategy: 'At networking events, ask about the person's role and how much they love working in the company, rather than just job openings or what the latest innovation in AI is—shows deeper interest.' – [Career Coach]",
  "📱 Tech Tip: 'Download Venmo, Zelle, and CashApp immediately—Americans rarely use cash for splitting bills.' – [2Y MBA]",
  "🗣️ Communication Hack: 'Struggling with communication? Book a session with the BCC, they really helped me – [1Y MBA]",
  "🚗 Transportation Hack: 'The GoTriangle transit app is free with your student ID—save on transporation expenses. Download the UMO app!' – [1Y MBA]",
  "📈 Recruiting Insight: 'Companies value your international experience, but you must explicitly connect it to their business needs. Show them the stuff you're made of!' – [2Y MBA]",
  "💻 Remote Work Tip: 'When networking virtually, use a virtual background of your home country's landmark—great conversation starter!' – [Recent Grad]",
  "🏦 Banking Advice: " Bank of America, not too far from campus offers special accounts for international students with no SSN required.' – [2Y MBA]",
  "👥 Team Projects: 'Volunteer to take meeting notes—improves your English and ensures you don't miss important context.' – [2Y MBA]",
  "📲 App Recommendation: 'Grammarly Premium is worth every penny for international students writing case analyses.' – [BCC Coach]",
  "🍳 Self-Care: 'Meal prep on Weekends—fast food gets expensive and unhealthy quickly. Plus it's a real time and money saver' – [2Y MBA]",
  "🏢 Office Hours Tip: 'Visit professors during office hours—they are always happy yo help' – [2Y MBA]",
  "✈️ Travel Hack: 'Book holiday flights 3 months in advance—prices triple closer to Thanksgiving and Christmas.' – [International Club President]",
  "🎤 Presentation Skill: 'Record yourself presenting and listen for filler words in your non-native English—awareness is the first step.' – [BCC Coach]",
  "💳 Budget Tip: 'Amazon offers 6 months of Amazon Prime free for students! Take advantage of it with your student email address.' – [KFBS Student]",
  "📊 Data Analysis: 'Take the optional Excel & Powerpoint workshop from Training The Street —Trust me, it will really help.' – [TA]",
  "🤝 Informational Interview: 'Ask alumni from your home country for 15-minute calls—they're usually eager to help fellow internationals.' – [Career Services]",
  "🔊 Accent Tip: 'Don't apologize for your accent, but do speak slightly slower during presentations for clarity.' – [Communication Professor]",
  "💸 Tax Advice: 'The University offers free tax preparation help for international students in February—complex but essential.' – [Financial Aid Officer]",
  "☎️ Alumni Connection: 'Use the KFBS alumni database to filter by your home country—direct connection opportunities.' – [Career Services]",
  "🚶 Coffee Chat Prep: 'Get used to "Small Talks"— it can help to build a connection with whoever you're speaking to' – [2Y MBA]",
  "📰 Current Events: 'Subscribe to Morning Brew newsletter—quick daily American business news in plain English.' – [Finance Club President]",
  "🤔 Cultural Context: 'Cold emails are normal in American business culture—don't hesitate to reach out to companies directly.' – [2Y MBA]",
  "🥘 Social Tip: 'Host an international potluck during orientation week—instant connections across cohorts.' – [MBASA President]",
  "⏰ Scheduling Hack: 'Americans often book meetings weeks in advance—don't be surprised by "Let's meet next month."' – [KFBS Alum]",
  "📋 Club Strategy: ' You can join as much as you want, but join at least one professional club and one diversity club—balanced networking portfolio.' – [2Y MBA]",
  "🏆 Case Competition: 'International perspectives are gold in case competitions—leverage your unique market knowledge.' – [Competition Winner]",
  "📅 Holiday Planning: 'Book an Airbnb with other international students during Thanksgiving break and travel to another city —campus gets very quiet.' – [KFBS Student]",
  "🏫 Campus Resource: 'The Business Communications Center (BCC) offers specific appointments to help review your resume, cover letter and even interview prep—book them early in the semester.' – [BCC Coach]",
  "🖨️ Printing Hack: 'Printing is free, there's a printer in CafeMcColl and also on the 1st floor of school near Room 2350, and it's free with your ONYEN' – [2Y MBA]",
  "🔄 Adaptation Advice: 'Observe first, then adapt. American business culture rewards those who can blend confidence with adaptability.' – [KFBS Alum]",

];

export function getDailyTip() {
  const tip = DAILY_TIPS[Math.floor(Math.random() * DAILY_TIPS.length)];
  return `Your MBA Tip of the Day': ${tip}`;
}
